/*
 Navicat Premium Data Transfer

 Source Server         : Mysql Server Test
 Source Server Type    : MySQL
 Source Server Version : 100411
 Source Host           : 10.0.1.32:3306
 Source Schema         : ss_scs

 Target Server Type    : MySQL
 Target Server Version : 100411
 File Encoding         : 65001

 Date: 07/12/2020 00:03:19
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for shop_test
-- ----------------------------
DROP TABLE IF EXISTS `shop_test`;
CREATE TABLE `shop_test`  (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 423 CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of shop_test
-- ----------------------------
INSERT INTO `shop_test` VALUES (1, 'ตัดสินค้าก่อนใช้ระบบ ');
INSERT INTO `shop_test` VALUES (2, 'นิคม304A (ปจ)');
INSERT INTO `shop_test` VALUES (3, 'นิคม304 (ปจ)');
INSERT INTO `shop_test` VALUES (4, 'อ่าวอุดม (ชบ)');
INSERT INTO `shop_test` VALUES (5, 'เอซี2 (ปท)');
INSERT INTO `shop_test` VALUES (6, 'อ่อนนุช (กท)');
INSERT INTO `shop_test` VALUES (7, 'อำนาจเจริญ');
INSERT INTO `shop_test` VALUES (8, 'อรัญประเทศ (สก)');
INSERT INTO `shop_test` VALUES (9, 'อ่างศิลา (ชบ)');
INSERT INTO `shop_test` VALUES (10, 'อมตะ1(ชบ)');
INSERT INTO `shop_test` VALUES (11, 'อมตะ3 (ชบ)');
INSERT INTO `shop_test` VALUES (12, 'อมตะ4 (ชบ)');
INSERT INTO `shop_test` VALUES (13, 'อมตะ5 (ชบ)');
INSERT INTO `shop_test` VALUES (14, 'อมตะ6 (ชบ)');
INSERT INTO `shop_test` VALUES (15, 'อมตะ7 (ชบ)');
INSERT INTO `shop_test` VALUES (16, 'อมตะ8 (ชบ)');
INSERT INTO `shop_test` VALUES (17, 'อมตะ9 (ชบ)');
INSERT INTO `shop_test` VALUES (18, 'อมตะA (ชบ)');
INSERT INTO `shop_test` VALUES (19, 'อ่างทอง');
INSERT INTO `shop_test` VALUES (20, 'อ้อมใหญ่ (นฐ)');
INSERT INTO `shop_test` VALUES (21, 'อยุธยา');
INSERT INTO `shop_test` VALUES (22, 'บางบอน (กท)');
INSERT INTO `shop_test` VALUES (23, 'บ้านผือ (อด)');
INSERT INTO `shop_test` VALUES (24, 'บ้านบึง (ชบ)');
INSERT INTO `shop_test` VALUES (25, 'บางบัวทอง (นบ)');
INSERT INTO `shop_test` VALUES (26, 'บ้านฉาง (รย)');
INSERT INTO `shop_test` VALUES (27, 'บ้านดุง (อด)');
INSERT INTO `shop_test` VALUES (28, 'บางใหญ่ (นบ)');
INSERT INTO `shop_test` VALUES (29, 'บางใหญ่2 (นบ)');
INSERT INTO `shop_test` VALUES (30, 'บึงกาฬ');
INSERT INTO `shop_test` VALUES (31, 'บางกรวย (นบ)');
INSERT INTO `shop_test` VALUES (32, 'บางเลน (นฐ)');
INSERT INTO `shop_test` VALUES (33, 'บ้านโป่ง (รบ)');
INSERT INTO `shop_test` VALUES (34, 'บางปลา (สป)');
INSERT INTO `shop_test` VALUES (35, 'บ้านไผ่ (ขก)');
INSERT INTO `shop_test` VALUES (36, 'บางพลี (สป)');
INSERT INTO `shop_test` VALUES (37, 'บางปะอิน (อย)');
INSERT INTO `shop_test` VALUES (38, 'บางปะอิน2 (อย)');
INSERT INTO `shop_test` VALUES (39, 'บ้านแพ้ว (สค)');
INSERT INTO `shop_test` VALUES (40, 'บางปู (สป)');
INSERT INTO `shop_test` VALUES (41, 'แบริ่ง (กท)');
INSERT INTO `shop_test` VALUES (42, 'บรบือ (มค)');
INSERT INTO `shop_test` VALUES (43, 'บุรีรัมย์');
INSERT INTO `shop_test` VALUES (44, 'บุรีรัมย์2');
INSERT INTO `shop_test` VALUES (45, 'บึงสามพัน (พช)');
INSERT INTO `shop_test` VALUES (46, 'บรรทัดทอง (กท)');
INSERT INTO `shop_test` VALUES (47, 'บ่อวิน2(รย)');
INSERT INTO `shop_test` VALUES (48, 'บ่อวิน3 (รย)');
INSERT INTO `shop_test` VALUES (49, 'บัวใหญ่ (นม)');
INSERT INTO `shop_test` VALUES (50, 'ชะอำ (พบ)');
INSERT INTO `shop_test` VALUES (51, 'โชคชัย (นม)');
INSERT INTO `shop_test` VALUES (52, 'เชียงคำ (พย)');
INSERT INTO `shop_test` VALUES (53, 'เชียงใหม่');
INSERT INTO `shop_test` VALUES (54, 'ชุมแพ (ขก)');
INSERT INTO `shop_test` VALUES (55, 'เชียงราย');
INSERT INTO `shop_test` VALUES (56, 'ชุมแสง (นว)');
INSERT INTO `shop_test` VALUES (57, 'ชุมพร');
INSERT INTO `shop_test` VALUES (58, 'ชัยนาท');
INSERT INTO `shop_test` VALUES (59, 'สหพัฒน์1 (ชบ)');
INSERT INTO `shop_test` VALUES (60, 'สหพัฒน์3 (ชบ)');
INSERT INTO `shop_test` VALUES (61, 'ฉะเชิงเทรา');
INSERT INTO `shop_test` VALUES (62, 'ชาติตระการ (พล)');
INSERT INTO `shop_test` VALUES (63, 'ชุมพวง (นม)');
INSERT INTO `shop_test` VALUES (64, 'ชัยภูมิ');
INSERT INTO `shop_test` VALUES (65, 'ด่านช้าง (สพ)');
INSERT INTO `shop_test` VALUES (66, 'ด่านขุนทด (นม)');
INSERT INTO `shop_test` VALUES (67, 'ดอนเมือง (กท)');
INSERT INTO `shop_test` VALUES (68, 'ดอนตูม (นฐ)');
INSERT INTO `shop_test` VALUES (69, 'เดชอุดม (อบ)');
INSERT INTO `shop_test` VALUES (70, 'เฟอร์-อำนาจเจริญ');
INSERT INTO `shop_test` VALUES (71, 'เฟอร์-อยุธยา');
INSERT INTO `shop_test` VALUES (72, 'เฟอร์-บางเลน2 (นฐ)');
INSERT INTO `shop_test` VALUES (73, 'เฟอร์-บ้านโป่ง2 (รบ)');
INSERT INTO `shop_test` VALUES (74, 'เฟอร์-บัวใหญ่2 (นม)');
INSERT INTO `shop_test` VALUES (75, 'เฟอร์-ชลบุรี');
INSERT INTO `shop_test` VALUES (76, 'เฟอร์-ชุมแพ2 (ขก)');
INSERT INTO `shop_test` VALUES (77, 'เฟอร์-ฉะเชิงเทรา2');
INSERT INTO `shop_test` VALUES (78, 'เฟอร์-ดอนเมือง (กท)');
INSERT INTO `shop_test` VALUES (79, 'เฟอร์-ห้วยปราบ1 (ชบ)');
INSERT INTO `shop_test` VALUES (80, 'เฟอร์-คลอง6 ธัญบุรี (ปท)');
INSERT INTO `shop_test` VALUES (81, 'เฟอร์-กระบี่2');
INSERT INTO `shop_test` VALUES (82, 'เฟอร์-กาญจนาภิเษก39 (สป)');
INSERT INTO `shop_test` VALUES (83, 'เฟอร์-ขอนแก่น');
INSERT INTO `shop_test` VALUES (84, 'เฟอร์-แก้งคร้อ2 (ชย)');
INSERT INTO `shop_test` VALUES (85, 'เฟอร์-กุมภวาปี2 (อด)');
INSERT INTO `shop_test` VALUES (86, 'เฟอร์-กำแพงเพชร2');
INSERT INTO `shop_test` VALUES (87, 'เฟอร์-คู้บอน (กท)');
INSERT INTO `shop_test` VALUES (88, 'เฟอร์-ลาดกระบัง (กท)');
INSERT INTO `shop_test` VALUES (89, 'เฟอร์-เลย2');
INSERT INTO `shop_test` VALUES (90, 'เฟอร์-มหาสารคาม');
INSERT INTO `shop_test` VALUES (91, 'เฟอร์-มาบตาพุต (รย)');
INSERT INTO `shop_test` VALUES (92, 'เฟอร์-นครชัยศรี (นฐ)');
INSERT INTO `shop_test` VALUES (93, 'เฟอร์-หนองม่วง (ลบ)');
INSERT INTO `shop_test` VALUES (94, 'เฟอร์-นิมิตรใหม่ (ปท)');
INSERT INTO `shop_test` VALUES (95, 'เฟอร์-นานาพลาซ่า (ปท)');
INSERT INTO `shop_test` VALUES (96, 'เฟอร์-นนทบุรี2');
INSERT INTO `shop_test` VALUES (97, 'เฟอร์-ปราณบุรี2 (ปข)');
INSERT INTO `shop_test` VALUES (98, 'เฟอร์-ภูเก็ต2');
INSERT INTO `shop_test` VALUES (99, 'เฟอร์-แพรกษา2 (สป)');
INSERT INTO `shop_test` VALUES (100, 'เฟอร์-พิษณุโลก3');
INSERT INTO `shop_test` VALUES (101, 'เฟอร์-พิมาย2 (นม)');
INSERT INTO `shop_test` VALUES (102, 'เฟอร์-ปทุมธานี3');
INSERT INTO `shop_test` VALUES (103, 'เฟอร์-พันท้ายนรสิงห์ (สค)');
INSERT INTO `shop_test` VALUES (104, 'เฟอร์-โรจนะA (อย)');
INSERT INTO `shop_test` VALUES (105, 'เฟอร์-สระบุรี2');
INSERT INTO `shop_test` VALUES (106, 'เฟอร์-สีคิ้ว2 (นม)');
INSERT INTO `shop_test` VALUES (107, 'เฟอร์-สามโคก (ปท)');
INSERT INTO `shop_test` VALUES (108, 'เฟอร์-สุพรรณบุรี2');
INSERT INTO `shop_test` VALUES (109, 'เฟอร์-สุราษฎร์ธานี2');
INSERT INTO `shop_test` VALUES (110, 'เฟอร์-ศรีสะเกษ2');
INSERT INTO `shop_test` VALUES (111, 'เฟอร์-สุขสวัสดิ์2 (สป)');
INSERT INTO `shop_test` VALUES (112, 'เฟอร์-สัตหีบ3 (ชบ)');
INSERT INTO `shop_test` VALUES (113, 'เฟอร์-ท้ายบ้าน2 (สป)');
INSERT INTO `shop_test` VALUES (114, 'เฟอร์-ตลาดไท (ปท)');
INSERT INTO `shop_test` VALUES (115, 'เฟอร์-ทุ่งสง');
INSERT INTO `shop_test` VALUES (116, 'เฟอร์-ตลาดเซฟวัน (นม)');
INSERT INTO `shop_test` VALUES (117, 'เฟอร์-วังสามหมอ (อด)');
INSERT INTO `shop_test` VALUES (118, 'เหมราช (สบ)');
INSERT INTO `shop_test` VALUES (119, 'ห้วยปราบ2 (ชบ)');
INSERT INTO `shop_test` VALUES (120, 'ห้วยปราบ3 (ชบ)');
INSERT INTO `shop_test` VALUES (121, 'ห้วยปราบ4 (ชบ)');
INSERT INTO `shop_test` VALUES (122, 'ห้วยปราบ5 (ชบ)');
INSERT INTO `shop_test` VALUES (123, 'สำนักงานใหญ่ (ปาริมา)');
INSERT INTO `shop_test` VALUES (124, 'หัวทะเล (นม)');
INSERT INTO `shop_test` VALUES (125, 'หัวทะเล2 (นม)');
INSERT INTO `shop_test` VALUES (126, 'หทัยราษฎร์ (กท)');
INSERT INTO `shop_test` VALUES (127, 'หาดใหญ่ (สข)');
INSERT INTO `shop_test` VALUES (128, 'ห้วยยอด (ตง)');
INSERT INTO `shop_test` VALUES (129, 'จันทบุรี');
INSERT INTO `shop_test` VALUES (130, 'จตุรัส (ชย)');
INSERT INTO `shop_test` VALUES (131, 'คลอง11 (ปท)');
INSERT INTO `shop_test` VALUES (132, 'คลอง7 พลาซ่า (ปท)');
INSERT INTO `shop_test` VALUES (133, 'คลอง8 (ปท)');
INSERT INTO `shop_test` VALUES (134, 'แก่งคอย (สบ)');
INSERT INTO `shop_test` VALUES (135, 'กบินทร์2 (ปจ)');
INSERT INTO `shop_test` VALUES (136, 'กบินทร์บุรี3 (ปจ)');
INSERT INTO `shop_test` VALUES (137, 'กระบี่');
INSERT INTO `shop_test` VALUES (138, 'ครบุรี (นม)');
INSERT INTO `shop_test` VALUES (139, 'กาญจนบุรี');
INSERT INTO `shop_test` VALUES (140, 'กาญจนาภิเษก39 (สป)');
INSERT INTO `shop_test` VALUES (141, 'กุฉินารายณ์ (กส)');
INSERT INTO `shop_test` VALUES (142, 'ขอนแก่นพลาซ่า');
INSERT INTO `shop_test` VALUES (143, 'ขอนแก่น4');
INSERT INTO `shop_test` VALUES (144, 'เขื่องใน (อบ)');
INSERT INTO `shop_test` VALUES (145, 'เคหะร่มเกล้า31 (กท)');
INSERT INTO `shop_test` VALUES (146, 'เคเค');
INSERT INTO `shop_test` VALUES (147, 'แก้งคร้อ1 (ชย)');
INSERT INTO `shop_test` VALUES (148, 'คำเขื่อนแก้ว (ยส)');
INSERT INTO `shop_test` VALUES (149, 'ขุขันธ์ (ศก)');
INSERT INTO `shop_test` VALUES (150, 'คลองหลวง (ปท)');
INSERT INTO `shop_test` VALUES (151, 'แกลง (รย)');
INSERT INTO `shop_test` VALUES (152, 'กมลาไสย (กส)');
INSERT INTO `shop_test` VALUES (153, 'เขมราฐ (อบ)');
INSERT INTO `shop_test` VALUES (154, 'กระนวน (ขก)');
INSERT INTO `shop_test` VALUES (155, 'โคราช (นม)');
INSERT INTO `shop_test` VALUES (156, 'เขาพนม (กบ)');
INSERT INTO `shop_test` VALUES (157, 'กุมภวาปี (อด)');
INSERT INTO `shop_test` VALUES (158, 'กำแพงเพชร');
INSERT INTO `shop_test` VALUES (159, 'กำแพงแสน (นฐ)');
INSERT INTO `shop_test` VALUES (160, 'กระสัง (บร)');
INSERT INTO `shop_test` VALUES (161, 'กันทรารมย์ (ศก)');
INSERT INTO `shop_test` VALUES (162, 'กาฬสินธุ์');
INSERT INTO `shop_test` VALUES (163, 'โกสุมพิสัย (มค)');
INSERT INTO `shop_test` VALUES (164, 'โคกสำโรง (ลบ)');
INSERT INTO `shop_test` VALUES (165, 'เกษตรวิสัย (รอ)');
INSERT INTO `shop_test` VALUES (166, 'กระทุ่มแบน (สค)');
INSERT INTO `shop_test` VALUES (167, 'กระทุ่มแบน2 (สค)');
INSERT INTO `shop_test` VALUES (168, 'กันทรลักษณ์ (ศก)');
INSERT INTO `shop_test` VALUES (169, 'กสิกรทุ่งสร้าง (ขก)');
INSERT INTO `shop_test` VALUES (170, 'กันทรวิชัย (มค)');
INSERT INTO `shop_test` VALUES (171, 'คู้บอน (กท)');
INSERT INTO `shop_test` VALUES (172, 'ร้อยเอ็ด');
INSERT INTO `shop_test` VALUES (173, 'ลพบุรี');
INSERT INTO `shop_test` VALUES (174, 'แหลมฉบัง (ชบ)');
INSERT INTO `shop_test` VALUES (175, 'ลำลูกกา (ปท)');
INSERT INTO `shop_test` VALUES (176, 'ลำลูกกา คลอง 8 (ปท)');
INSERT INTO `shop_test` VALUES (177, 'ลาดหลุมแก้ว (ปท)');
INSERT INTO `shop_test` VALUES (178, 'ลำนารายณ์ (ลบ)');
INSERT INTO `shop_test` VALUES (179, 'เลิงนกทา (ยส)');
INSERT INTO `shop_test` VALUES (180, 'เลย');
INSERT INTO `shop_test` VALUES (181, 'ลำปาง');
INSERT INTO `shop_test` VALUES (182, 'ลาดปลาดุก (นบ)');
INSERT INTO `shop_test` VALUES (183, 'ลาดปลาเค้า (กท)');
INSERT INTO `shop_test` VALUES (184, 'ลำพูน');
INSERT INTO `shop_test` VALUES (185, 'หล่มสัก (พช)');
INSERT INTO `shop_test` VALUES (186, 'หลังสวน (ชพ)');
INSERT INTO `shop_test` VALUES (187, 'ลาดสวาย (ปท)');
INSERT INTO `shop_test` VALUES (188, 'ลาดยาว (นว)');
INSERT INTO `shop_test` VALUES (189, 'แม่สอด (ตก)');
INSERT INTO `shop_test` VALUES (190, 'โมบาย (ปท)');
INSERT INTO `shop_test` VALUES (191, 'โมบาย4 (ปท)');
INSERT INTO `shop_test` VALUES (192, 'มีนบุรี (กท)');
INSERT INTO `shop_test` VALUES (193, 'มหาชัยA (สค)');
INSERT INTO `shop_test` VALUES (194, 'มหาชัยB (สค)');
INSERT INTO `shop_test` VALUES (195, 'มุกดาหาร');
INSERT INTO `shop_test` VALUES (196, 'มังกร (สป)');
INSERT INTO `shop_test` VALUES (197, 'มัญจาคีรี (ขก)');
INSERT INTO `shop_test` VALUES (198, 'แม่กลอง (สส)');
INSERT INTO `shop_test` VALUES (199, 'มวกเหล็ก (สบ)');
INSERT INTO `shop_test` VALUES (200, 'เมืองพล (ขก)');
INSERT INTO `shop_test` VALUES (201, 'มีทรัพย์');
INSERT INTO `shop_test` VALUES (202, 'มหาสารคาม2');
INSERT INTO `shop_test` VALUES (203, 'ม่วงสามสิบ (อบ)');
INSERT INTO `shop_test` VALUES (204, 'แม่แตง (ชม)');
INSERT INTO `shop_test` VALUES (205, 'มาบตาพุด (รย)');
INSERT INTO `shop_test` VALUES (206, 'มาบตาพุด2 (รย)');
INSERT INTO `shop_test` VALUES (207, 'มาบยางพร (รย)');
INSERT INTO `shop_test` VALUES (208, 'มาบยางพร2 (รย)');
INSERT INTO `shop_test` VALUES (209, 'มาบยางพรA (รย)');
INSERT INTO `shop_test` VALUES (210, 'นานา2 (ปท)');
INSERT INTO `shop_test` VALUES (211, 'นาแก (นพ)');
INSERT INTO `shop_test` VALUES (212, 'น่าน');
INSERT INTO `shop_test` VALUES (213, 'นานา (ปท)');
INSERT INTO `shop_test` VALUES (214, 'หนองบัวลำภู');
INSERT INTO `shop_test` VALUES (215, 'หนองบุญมาก (นม)');
INSERT INTO `shop_test` VALUES (216, 'หนองฉาง (อน)');
INSERT INTO `shop_test` VALUES (217, 'หนองซาก (ชบ)');
INSERT INTO `shop_test` VALUES (218, 'งามวงศ์วาน (นบ)');
INSERT INTO `shop_test` VALUES (219, 'หนองหาน (อด)');
INSERT INTO `shop_test` VALUES (220, 'หนองจอก (กท)');
INSERT INTO `shop_test` VALUES (221, 'นิคมพัฒนา1 (รย)');
INSERT INTO `shop_test` VALUES (222, 'หนองคาย');
INSERT INTO `shop_test` VALUES (223, 'หนองแค (สบ)');
INSERT INTO `shop_test` VALUES (224, 'นาเกลือ (ชบ)');
INSERT INTO `shop_test` VALUES (225, 'นาแขม (ปจ)');
INSERT INTO `shop_test` VALUES (226, 'นิคมพัฒนา2(รย)');
INSERT INTO `shop_test` VALUES (227, 'นครพนม');
INSERT INTO `shop_test` VALUES (228, 'นครศรีธรรมราช');
INSERT INTO `shop_test` VALUES (229, 'นครศรีธรรมราช2');
INSERT INTO `shop_test` VALUES (230, 'นครปฐม');
INSERT INTO `shop_test` VALUES (231, 'นครปฐม2');
INSERT INTO `shop_test` VALUES (232, 'นครไทย (พล)');
INSERT INTO `shop_test` VALUES (233, 'นครนายก');
INSERT INTO `shop_test` VALUES (234, 'หนองมน (ชบ)');
INSERT INTO `shop_test` VALUES (235, 'โนนสูง (นม)');
INSERT INTO `shop_test` VALUES (236, 'น้ำพอง (ขก)');
INSERT INTO `shop_test` VALUES (237, 'นางรอง (บร)');
INSERT INTO `shop_test` VALUES (238, 'นครสวรรค์');
INSERT INTO `shop_test` VALUES (239, 'นนทบุรี');
INSERT INTO `shop_test` VALUES (240, 'นวB (ปท)');
INSERT INTO `shop_test` VALUES (241, 'นวมินทร์ (กท)');
INSERT INTO `shop_test` VALUES (242, 'น้ำยืน (อบ)');
INSERT INTO `shop_test` VALUES (243, 'องครักษ์ (นย)');
INSERT INTO `shop_test` VALUES (244, 'โอนไประบบเก่า');
INSERT INTO `shop_test` VALUES (245, 'ปราณบุรี (ปข)');
INSERT INTO `shop_test` VALUES (246, 'เพชรบุรี');
INSERT INTO `shop_test` VALUES (247, 'พิบูลมังสาหาร (อบ)');
INSERT INTO `shop_test` VALUES (248, 'ปากช่อง (นม)');
INSERT INTO `shop_test` VALUES (249, 'ปลวกแดงเอ (รย)');
INSERT INTO `shop_test` VALUES (250, 'ปลวกแดงบี (รย)');
INSERT INTO `shop_test` VALUES (251, 'ปลวกแดงดี(รย)');
INSERT INTO `shop_test` VALUES (252, 'เพ็ญ (อด)');
INSERT INTO `shop_test` VALUES (253, 'ภาชี (อย)');
INSERT INTO `shop_test` VALUES (254, 'เพชรบูรณ์');
INSERT INTO `shop_test` VALUES (255, 'ภูเก็ต');
INSERT INTO `shop_test` VALUES (256, 'แพร่');
INSERT INTO `shop_test` VALUES (257, 'พระแสง (สฎ)');
INSERT INTO `shop_test` VALUES (258, 'สีชมพู (ขก)');
INSERT INTO `shop_test` VALUES (259, 'พิจิตร');
INSERT INTO `shop_test` VALUES (260, 'ปราจีนบุรี');
INSERT INTO `shop_test` VALUES (261, 'ปิ่นเกล้าพลาซ่า (กท)');
INSERT INTO `shop_test` VALUES (262, 'ประโคนชัย (บร)');
INSERT INTO `shop_test` VALUES (263, 'ภูเขียว (ชย)');
INSERT INTO `shop_test` VALUES (264, 'เพชรเกษม81 (กท)');
INSERT INTO `shop_test` VALUES (265, 'พังโคน (สน)');
INSERT INTO `shop_test` VALUES (266, 'แพรกษา (สป)');
INSERT INTO `shop_test` VALUES (267, 'พิษณุโลก');
INSERT INTO `shop_test` VALUES (268, 'พิษณุโลก2');
INSERT INTO `shop_test` VALUES (269, 'พิมาย (นม)');
INSERT INTO `shop_test` VALUES (270, 'พิมลราช (นบ)');
INSERT INTO `shop_test` VALUES (271, 'โป่งเมืองพัทยา (ชบ)');
INSERT INTO `shop_test` VALUES (272, 'พระอินทร์ (อย)');
INSERT INTO `shop_test` VALUES (273, 'พระอินทร์2 (อย)');
INSERT INTO `shop_test` VALUES (274, 'พังงา');
INSERT INTO `shop_test` VALUES (275, 'พรประภานิมิตร (ชบ)');
INSERT INTO `shop_test` VALUES (276, 'พนมสารคาม (ฉช)');
INSERT INTO `shop_test` VALUES (277, 'พระปิ่น3(นบ)');
INSERT INTO `shop_test` VALUES (278, 'พระพุทธบาท (สบ)');
INSERT INTO `shop_test` VALUES (279, 'ปราสาท (สร)');
INSERT INTO `shop_test` VALUES (280, 'พระสมุทรเจดีย์ (สป)');
INSERT INTO `shop_test` VALUES (281, 'ปทุมธานี');
INSERT INTO `shop_test` VALUES (282, 'ปทุมธานี2');
INSERT INTO `shop_test` VALUES (283, 'ปทุมธานี4');
INSERT INTO `shop_test` VALUES (284, 'ปักธงชัย (นม)');
INSERT INTO `shop_test` VALUES (285, 'พานทอง (ชบ)');
INSERT INTO `shop_test` VALUES (286, 'โพนทอง (รอ)');
INSERT INTO `shop_test` VALUES (287, 'ประทาย (นม)');
INSERT INTO `shop_test` VALUES (288, 'พัทลุง');
INSERT INTO `shop_test` VALUES (289, 'พุทธมณฑลสาย5 (นฐ)');
INSERT INTO `shop_test` VALUES (290, 'พัทยา1 (ชบ)');
INSERT INTO `shop_test` VALUES (291, 'พัทยา2 (ชบ)');
INSERT INTO `shop_test` VALUES (292, 'ภูเวียง (ขก)');
INSERT INTO `shop_test` VALUES (293, 'พยัคฆภูมิ (มค)');
INSERT INTO `shop_test` VALUES (294, 'พระยาสุเรนทร์ (กท)');
INSERT INTO `shop_test` VALUES (295, 'ราชบุรี');
INSERT INTO `shop_test` VALUES (296, 'ร่มเกล้า (กท)');
INSERT INTO `shop_test` VALUES (297, 'รามอินทรา (กท)');
INSERT INTO `shop_test` VALUES (298, 'โรจนะ2 (อย)');
INSERT INTO `shop_test` VALUES (299, 'โรจนะ3 (อย)');
INSERT INTO `shop_test` VALUES (300, 'โรจนะ304 (ปจ)');
INSERT INTO `shop_test` VALUES (301, 'โรจนะ4(อย)');
INSERT INTO `shop_test` VALUES (302, 'โรจนะA (อย)');
INSERT INTO `shop_test` VALUES (303, 'รังสิต1 (ปท)');
INSERT INTO `shop_test` VALUES (304, 'โรงกษาปณ์ (ปท)');
INSERT INTO `shop_test` VALUES (305, 'ระนอง');
INSERT INTO `shop_test` VALUES (306, 'ราษฎร์พัฒนา (กท)');
INSERT INTO `shop_test` VALUES (307, 'รัตนาธิเบศร์ (นบ)');
INSERT INTO `shop_test` VALUES (308, 'ระยอง');
INSERT INTO `shop_test` VALUES (309, 'สระแก้ว');
INSERT INTO `shop_test` VALUES (310, 'สตูล');
INSERT INTO `shop_test` VALUES (311, 'สระบุรี');
INSERT INTO `shop_test` VALUES (312, 'ศรีบุญเรือง (นภ)');
INSERT INTO `shop_test` VALUES (313, 'สิงห์บุรี');
INSERT INTO `shop_test` VALUES (314, 'สิชล (นศ)');
INSERT INTO `shop_test` VALUES (315, 'สอยดาว (จบ)');
INSERT INTO `shop_test` VALUES (316, 'เซกา (บก)');
INSERT INTO `shop_test` VALUES (317, 'สีคิ้ว (นม)');
INSERT INTO `shop_test` VALUES (318, 'สกลนคร');
INSERT INTO `shop_test` VALUES (319, 'สกลนคร1');
INSERT INTO `shop_test` VALUES (320, 'สังขะ (สร)');
INSERT INTO `shop_test` VALUES (321, 'สรรคบุรี (ชน)');
INSERT INTO `shop_test` VALUES (322, 'สงขลา');
INSERT INTO `shop_test` VALUES (323, 'สามโคก (ปท)');
INSERT INTO `shop_test` VALUES (324, 'สุโขทัย');
INSERT INTO `shop_test` VALUES (325, 'สลกบาตร (กพ)');
INSERT INTO `shop_test` VALUES (326, 'เสลภูมิ (รอ)');
INSERT INTO `shop_test` VALUES (327, 'ศาลายา (นฐ)');
INSERT INTO `shop_test` VALUES (328, 'สายไหม (กท)');
INSERT INTO `shop_test` VALUES (329, 'ศรีมหาโพธิ์ (ปจ)');
INSERT INTO `shop_test` VALUES (330, 'ไทรน้อย (นบ)');
INSERT INTO `shop_test` VALUES (331, 'สนามชัยเขต (ฉช)');
INSERT INTO `shop_test` VALUES (332, 'ศรีสัชนาลัย (สท)');
INSERT INTO `shop_test` VALUES (333, 'สูงเนิน (นม)');
INSERT INTO `shop_test` VALUES (334, 'ศรีนครินทร์ (กท)');
INSERT INTO `shop_test` VALUES (335, 'สมเด็จ (กส)');
INSERT INTO `shop_test` VALUES (336, 'สุพรรณบุรี');
INSERT INTO `shop_test` VALUES (337, 'สะพานใหม่ (กท)');
INSERT INTO `shop_test` VALUES (338, 'สามพราน (นฐ)');
INSERT INTO `shop_test` VALUES (339, 'สะพานสี่ (รย)');
INSERT INTO `shop_test` VALUES (340, 'สำโรง2 (สป)');
INSERT INTO `shop_test` VALUES (341, 'ศรีราชา (ชบ)');
INSERT INTO `shop_test` VALUES (342, 'สุรินทร์');
INSERT INTO `shop_test` VALUES (343, 'สุรินทร์2');
INSERT INTO `shop_test` VALUES (344, 'สำโรงเหนือ (สป)');
INSERT INTO `shop_test` VALUES (345, 'สารภี (ชม)');
INSERT INTO `shop_test` VALUES (346, 'สุราษฎร์ธานี');
INSERT INTO `shop_test` VALUES (347, 'เสิงสาง (นม)');
INSERT INTO `shop_test` VALUES (348, 'สินสมบูรณ์2(ปท)');
INSERT INTO `shop_test` VALUES (349, 'สินสมบูรณ์3 (ปท)');
INSERT INTO `shop_test` VALUES (350, 'สันทราย (ชม)');
INSERT INTO `shop_test` VALUES (351, 'ศรีสะเกษ');
INSERT INTO `shop_test` VALUES (352, 'สุขสวัสดิ์ (สป)');
INSERT INTO `shop_test` VALUES (353, 'สุขสวัสดิ์3 (สป)');
INSERT INTO `shop_test` VALUES (354, 'ศรีเทพ (พช)');
INSERT INTO `shop_test` VALUES (355, 'สัตหีบ (ชบ)');
INSERT INTO `shop_test` VALUES (356, 'สัตหีบ2 (ชบ)');
INSERT INTO `shop_test` VALUES (357, 'สุวรรณภูมิ (รอ)');
INSERT INTO `shop_test` VALUES (358, 'สุวินทวงศ์ (ฉช)');
INSERT INTO `shop_test` VALUES (359, 'สว่างแดนดิน (สน)');
INSERT INTO `shop_test` VALUES (360, 'สวรรคโลก (สท)');
INSERT INTO `shop_test` VALUES (361, 'ตาก');
INSERT INTO `shop_test` VALUES (362, 'ท้ายบ้าน (สป)');
INSERT INTO `shop_test` VALUES (363, 'ท่าบ่อ (นค)');
INSERT INTO `shop_test` VALUES (364, 'ถลาง (ภก)');
INSERT INTO `shop_test` VALUES (365, 'ท่าอิฐ (นบ)');
INSERT INTO `shop_test` VALUES (366, 'ท่าอิฐ2(นบ)');
INSERT INTO `shop_test` VALUES (367, 'ท่าข้าม (กท)');
INSERT INTO `shop_test` VALUES (368, 'ตาคลี (นว)');
INSERT INTO `shop_test` VALUES (369, 'ทุ่งครุ (กท)');
INSERT INTO `shop_test` VALUES (370, 'ทับคล้อ (พจ)');
INSERT INTO `shop_test` VALUES (371, 'ตระกาลพืชผล (อบ)');
INSERT INTO `shop_test` VALUES (372, 'ตะเคียนเตี้ย (ชบ)');
INSERT INTO `shop_test` VALUES (373, 'ตลาดเขต (กจ)');
INSERT INTO `shop_test` VALUES (374, 'ท่าม่วง (กจ)');
INSERT INTO `shop_test` VALUES (375, 'ท่ามะกา (กจ)');
INSERT INTO `shop_test` VALUES (376, 'ช่างนานา');
INSERT INTO `shop_test` VALUES (377, 'ถนนเศรษฐกิจ (สค)');
INSERT INTO `shop_test` VALUES (378, 'ตลาดหนองใหญ่ (ขก)');
INSERT INTO `shop_test` VALUES (379, 'ตะพานหิน (พจ)');
INSERT INTO `shop_test` VALUES (380, 'ธาตุพนม (นพ)');
INSERT INTO `shop_test` VALUES (381, 'เทพารักษ์ (สป)');
INSERT INTO `shop_test` VALUES (382, 'เทพประสิทธิ์ (ชบ)');
INSERT INTO `shop_test` VALUES (383, 'ตราด');
INSERT INTO `shop_test` VALUES (384, 'ตรัง');
INSERT INTO `shop_test` VALUES (385, 'ทุ่งสง (นศ)');
INSERT INTO `shop_test` VALUES (386, 'ทุ่งสง2 (นศ)');
INSERT INTO `shop_test` VALUES (387, 'ท่าศาลา (นศ)');
INSERT INTO `shop_test` VALUES (388, 'เตาถ่าน (ชบ)');
INSERT INTO `shop_test` VALUES (389, 'ท่ายาง (พบ)');
INSERT INTO `shop_test` VALUES (390, 'ตลาดย่าโม (นม)');
INSERT INTO `shop_test` VALUES (391, 'อุบลราชธานี');
INSERT INTO `shop_test` VALUES (392, 'อุบลราชธานี2');
INSERT INTO `shop_test` VALUES (393, 'อุบลราชธานี3');
INSERT INTO `shop_test` VALUES (394, 'อุดรธานี');
INSERT INTO `shop_test` VALUES (395, 'อุดรธานี2');
INSERT INTO `shop_test` VALUES (396, 'อุดรธานี3');
INSERT INTO `shop_test` VALUES (397, 'อู่ทอง (สพ)');
INSERT INTO `shop_test` VALUES (398, 'อุตรดิตถ์');
INSERT INTO `shop_test` VALUES (399, 'อุทุมพรพิสัย (สก)');
INSERT INTO `shop_test` VALUES (400, 'อุทัยธานี');
INSERT INTO `shop_test` VALUES (401, 'วัดเกาะ (กท)');
INSERT INTO `shop_test` VALUES (402, 'วังน้อย (อย)');
INSERT INTO `shop_test` VALUES (403, 'วรกิจ (ชบ)');
INSERT INTO `shop_test` VALUES (404, 'วัชรพล (กท)');
INSERT INTO `shop_test` VALUES (405, 'วานรนิวาส (สน)');
INSERT INTO `shop_test` VALUES (406, 'วังน้ำเย็น (สก)');
INSERT INTO `shop_test` VALUES (407, 'วารินชำราบ (อบ)');
INSERT INTO `shop_test` VALUES (408, 'วังสะพุง (ลย)');
INSERT INTO `shop_test` VALUES (409, 'วังทอง (พล)');
INSERT INTO `shop_test` VALUES (410, 'ยโสธร');
INSERT INTO `shop_test` VALUES (411, 'ยางตลาด (กส)');
INSERT INTO `shop_test` VALUES (412, 'ตัดของขาด');
INSERT INTO `shop_test` VALUES (413, 'สินค้าที่ส่งไปซ่อม');
INSERT INTO `shop_test` VALUES (414, 'สำนักงานใหญ่ (ปท)');
INSERT INTO `shop_test` VALUES (416, 'ทดสอบ50');
INSERT INTO `shop_test` VALUES (417, 'ทดสอบshop');
INSERT INTO `shop_test` VALUES (418, 'ทดสอบshoptest');
INSERT INTO `shop_test` VALUES (419, 'ทดสอบshoptest');
INSERT INTO `shop_test` VALUES (420, 'ทดสอบshoptest');
INSERT INTO `shop_test` VALUES (422, 'ทดสอบshoptest');

SET FOREIGN_KEY_CHECKS = 1;
